---
title: "practical8"
author: "Harshal Marathe"
date: "2023-10-20"
output: word_document
---
```{r}
#Q1
x=c(0,1,2,3,4,5,6,7,8)
p_x=c(0,2/34,6/34,7/34,9/34,4/34,1/34,4/34,1/34)
df <- data.frame(x,p_x)
library(ggplot2)
spike_plot <- ggplot(data=df,mapping = aes(x=x,y=p_x))+
  geom_segment(mapping = aes(xend=x,yend=0),size=1,color="blue")+
  geom_point(pch=10,size=2,color="Red")+
  labs(title="PMF plot",x="X",y="probability")+
  theme_classic() 
spike_plot

library(plotly)
ggplotly(spike_plot)


F_x <- cumsum(p_x)
data <- data.frame(x,F_x)
cdf_plot <- ggplot(data=df,mapping = aes(x=x,y=F_x))+
  geom_step(size=1,color="blue")+
  geom_point(pch=10,size=2,color="Red")+
  labs(title="PMF plot",x="X",y="probability")+
  theme_minimal()
cdf_plot
ggplotly(cdf_plot)
```
```{r}
#Q2
prob_=choose(4,3)*choose(5,3)/choose(9,6)
# OR
dhyper(3,4,5,6)
# R code: 5.3
pnorm(2) # compute P(X<=2)
pnorm(2.5)-pnorm(0.84) #compute P(0.84<X<0=2.5)
1-pnorm(2) # compute P(X>2)
qnorm(0.5) # computes x such that P(X<=x)=0.5
```

```{r}
#Q3
# R code: 5.4
x=c(0.894, 0.235, 0.071, 0.459, 0.1, 0.991, 0.424, 0.159,
0.431,0.919, 0.061, 0.216, 0.082, 0.092, 0.9, 0.186, 0.579,
1.653,0.83, 0.093, 0.311, 0.429, 2.01, 1.718, 0.041, 0.817,
0.612,0.158, 0.099, 0.712, 2.267, 0.143, 0.527, 0.162, 0.994,
0.091,0.055, 1.033, 0.076, 0.149, 0.139, 0.752, 2.863, 0.107,
0.866,0.083, 0.188, 0.365, 0.278, 0.054)
hist(x,freq=F,xlab="Interarrival Times",main="",xlim=c(0,3),ylim=c(0,1.5))
# OR
hist(x,prob=T,xlab="Interarrival Times",main="", xlim=c(0,3),ylim=c(0,2))
lambda_hat=1/mean(x) # Rate is reciprocal of
 # mean
x=sort(x)
y=round(dexp(x, lambda_hat),2)
lines(x,y,type="o",pch=16,lwd=2)
#text(locator(1),"Histogram and",cex=0.8)
#text(locator(1),"Exponential density with parameter 1.8",cex=0.8)
```

```{r}
#Q4
t=c(840,157,145,44, 33,121,150,280, 434, 736, 584, 887,
 263,1901, 695, 294, 562, 721, 76, 710, 46, 402, 194,
 759,319, 460, 40,1336, 335, 1334, 454, 36, 667, 40,
 556, 99, 304, 375, 567, 139, 780, 203, 436, 30, 384,
 129, 9, 209, 599, 83, 832, 328, 246, 1617, 638, 937,
 735, 38, 365, 92, 82, 220)
n=length(t)
est_lambda=1/mean(t) # Estimate of lambda
d=c(rep(1,62)) # To assign frequency for each
 # value in t
cd=cumsum(d) # cumulative frequency
em_sf=(n-cd)/n # Empirical survival function
t=sort(t)
est_sf=exp(-est_lambda*t) # Estimated survival
 # function
plot(t,em_sf,type="o",col=2,pch=1,lwd=2,xlab="w
aiting time",ylab="survival function")
# To add the plot of estimated exp survival fun
points(t,est_sf,type="o",pch=2)
#legend(locator(1),legend=c("Empirical","Estimated Exponential"),pch=1:2,cex=0.7)
```
```{r}
#Q5
par(mfrow = c(1, 2)) 
f=function(x) 
{
y = 3/4 * (1 - x^2)
y[x < -1 | x > 1] = 0
return(y)
}
curve(f, -2, 2, xlab = "x", ylab = "f(x)", main = 
"PDF for X")
F_=function(x) {
 y = -x^3/4 + 3 * x/4 + 1/2
 y[x <= -1] = 0
 y[x > 1] = 1
 return(y)
}
curve(F_, -2, 2, xlab = "x", ylab = "F(x)", main = 
"CDF for X")
fx=function(x) {
 3/4 - 3/4 * x^2
} # define function fx
integrate(fx, lower = -0.5, upper = 1)
ans=integrate(fx, lower = -0.5, upper = 1)$value
ans
library(MASS) # for fractions() function
fractions(ans) # find closest fraction
par(mfrow = c(1, 1))

integrate(dnorm, -1.96, 1.96)
```

```{r}
#Q6
```

```{r}
#Q7
f=function(x){
y=630/56*x^4*(1-x^4)
}
curve(f, 0,1, xlab = "x", ylab = "630/56*x^4*(1-
x^4)")
e_x=function(x){x*f(x)}
E_X=integrate(e_x,0,1)
e_x2=function(x){x^2*f(x)}
E_X2=integrate(e_x2,0,1)
Var_X=E_X2$value-(E_X$value)^2
cbind(E_X$value,E_X2$value,Var_X)
Prob_=integrate(f,0.20,0.80)
Prob_$value

```

```{r}
#Q8
set.seed(33)
U=runif(10000)
X=sqrt((2 - sqrt(4 - 3 * U)))
Sample_Mean =mean(X)
Sample_Var=var(X)
f=function(x){4/3*x*(2-x^2)}
curve(f, 0, 1, xlab = "x")
e_x=function(x){x*f(x)}
E_X=integrate(e_x,0,1)
e_x2=function(x){x^2*f(x)}
E_X2=integrate(e_x2,0,1)
Var_X=E_X2$value-(E_X$value)^2
cbind(Sample_Mean,E_X$value,Sample_Var,Var_X)

```
```{r}
#Q9
scores=c(119, 107, 96, 107, 97, 103, 94, 106, 87, 
112,99, 99, 90,106, 110,99, 105, 100, 100, 94)
n=length(scores)
x=(1:n-0.5)/n
# OR
x=ppoints(n)
x_s=qnorm(x)
y_s=sort(scores)
plot(x_s,y_s)
# OR 
qqnorm(scores)
qqline(scores)
eda(scores)
```

```{r}
#Q10
t=c(840,157,145,44, 33,121,150,280, 434, 736, 584, 887, 
 263,1901, 695, 294, 562, 721, 76, 710, 46, 402, 194, 
 759,319, 460, 40,1336, 335, 1334, 454, 36, 667, 40, 
 556, 99, 304, 375, 567, 139, 780, 203, 436, 30, 384, 
 129, 9, 209, 599, 83, 832, 328, 246, 1617, 638, 937, 
 735, 38, 365, 92, 82, 220)
#install.packages("fitdistrplus")
library("fitdistrplus")
F1=fitdist(t,"exp")
summary(F1)
F2=fitdist(t,"gamma")
summary(F2)
F3=fitdist(t,"weibull")
summary(F3)
gofstat(list(F1,F2,F3),fitnames = c("exp", "gamma" 
,"weibull"))
par(mfrow=c(2,2))
plot.legend <- c("Exponential")
denscomp(list(F1), legendtext = plot.legend)
qqcomp(list(F1), legendtext = plot.legend)
cdfcomp(list(F1), legendtext = plot.legend)
ppcomp(list(F1), legendtext = plot.legend)
```
```{r}
#Q11
x=rbinom(20,1,0.5)
p=seq(0.1,0.9,0.001)
negloglike=function(p){-(sum(x)*log(p)+sum(1-x)*log(1-p))}
nlm(negloglike,0.5)
nlm(negloglike,0.5)$estimate
plot(p,-negloglike(p),type="n")
abline(v=mean(x),col=13,lwd=3)
lines(p,-negloglike(p),col=6,lwd=3)
loglike=function(p){(sum(x)*log(p)+sum(1-
x)*log(1-p))}
optimize(f=loglike,interval=c(0,1),maximum = T)
```





