---
title: "Practical 1"
author: "Harshal Marathe"
date: "2023-08-09"
output:
  html_document:
    df_print: paged
---



#Questions
```r{}

```
##Q1


```{r ,echo=T }

rm(list=ls())
tourist <- matrix(data=c(9.303,9.536,9.918,7.959,7.736,8.875,15.224,15.629,16.090,0.905,0.894,0.883,7.463,18.635,20.148),nrow=5,byrow=T)
dim(tourist)
Nationality <- c("germany","France","Great Britain","USA","Rest of the world")
year <- c("2003","2004","2005")
dimnames(tourist) <- list(Nationality,year)
tourist
#row sum
row_sum <- apply(tourist,1,sum)
row_sum

#col_sum 
col_sum<- apply(tourist,2,sum)
col_sum

#row means
row_mean=apply(tourist,1,mean)
row_mean
#Or
#rowMeans(tourist)


#col means
col_means=apply(tourist,2,mean)
col_means
#or
#colMeans(tourist)



```
##Q2
```{r}
#A=coefficient of X,y,z)
A <- matrix(c(3,2,1,2,-3,1,1,1,1),nrow=3,byrow=T)
#B=answer of the solution)
B <- matrix(c(10,-1,6),nrow=3)
#Values of X ,Y and Z
U=solve(A,B)
data.frame(W=c('X','Y','Z'),U)
#to find regular inverse
solve(A)%*%A


```
##Q3
```{r}
age <- c(25,30,18)
gender <- c("M","F","F")
weight<- c(116,115,120)
#cbind
S <- cbind(age,gender,weight)
S
#rbind
W <- rbind(age,gender,weight)
t(W)
#data.frame
Y <- data.frame(age,gender,weight)
Y
#is.data.frame- to check whether is it data frame or not 
is.data.frame(Y)
#as.matrix(Y)- changes a data frame to matrix
as.matrix(Y)
#is.matrix(Y)- to check whether is it a matrix or not
is.matrix(Y)

#another way
#my_data <- data.frame(age=numeric(0),gender=character(0),weight=numeric(0))
#my_data <- edit(my_data)

#another way
my_data_txt <- "
age gender weight
25   M     166
30   F     115
18   F     120
"
mydata_=read.table(header=T,text= my_data_txt)
mydata_



```
##Q4
```{r}
#data.frame
Manager <- c(1:5)
date <- c("10/24/08","10/28/08","10/01/08","10/12/08","05/01/09")
Country <- c("US","US","UK","UK","UK")
Gender <- c("M","F","F","M","F")
Age <- c(32,45,25,39,99)
q1 <- c(5,3,3,3,2)
q2 <- c(4,5,5,3,2)
q3 <- c(5,2,5,4,1)
q4 <- c(5,5,5,NA,2)
q5 <- c(5,5,2,NA,1)
Y <- data.frame(Manager,date,Country,Gender,Age,q1,q2,q3,q4,q5)
Y
my_data <- data.frame()
#D1 <- data.frame(Manager=numeric(0),date=character(0),Country=character(0),Gender=character(0),Age=numeric(0),q1=numeric(0),q2=numeric(0),q3=numeric(0),q4=numeric(0),q5=numeric(0))
#de <- edit(D1)
#print(de)

#another way
mydata <- "
Manager  date     Country  Gender  Age  q1  q2  q3  q4  q5
1       10/24/08   US       M       32   5  3   3    3   2




"
```
##Q5
```{r}
library(MASS)
data(Cars93)
fix(Cars93)
head(Cars93,n=10)
tail(Cars93)
###a)
attach(Cars93)
# 2x2 contigency table
table(Origin,AirBags)
detach(Cars93)
#Or
table(Cars93$Origin,Cars93$AirBags)

###b)
attach(Cars93)
ftable(Origin,AirBags,DriveTrain)
detach(Cars93)
#or
tab <- ftable(Cars93$Origin,Cars93$AirBags,Cars93$DriveTrain)

##c)
#margin.table ?
OA <- table(Cars93$Origin,Cars93$AirBags)
OA
#sum of the table
margin.table(OA,1)
margin.table(OA,2)
#proportion of the table
prop.table(OA)
prop.table(OA,1)
prop.table(OA,2)
```


##Q6
```{r}

install.packages("ISLR2")
library(ISLR2)
data(College)

head(College)# dimensions of the table 
dim(College)
#a)
summary(College)

#b)Scatter plot
pairs(College[,1:10])

#c)
boxplot(Outstate~Private,data=College)

#d)
Eliteclass <- ifelse(College$Top10perc>50,"Elite","Not Elite")
```


