---
title: "Tidyr"
author: "Harshal Marathe"
date: "2023-08-23"
output:
  word_document: default
  html_document: default
---
```{r}
#que1
#install.packages("tidyr")
library("tidyr")
library("dplyr")

#a)
table1 %>% mutate(rate=cases/population*10000)

#b)
table1 %>% count(year,wt=cases)
#c)
table4a
table4a %>% gather("1999","2000",key=year,value=cases)
  
table4b
table4b %>% gather("1999","2000",key=year,value=population)

table2
table2 %>% spread(key=type,value=count)
  
#d)
table4a 
ta<- table4a %>% gather('1999','2000',key="year",value="cases")
table4b
tb<- table4b %>% gather('1999','2000',key="year",value='population')
left_join(ta,tb)

#e)
table3
table3 %>% separate(rate,into=c("Cases","Population"))
table3 %>% separate(rate,into=c("Cases","Population"),convert=TRUE)

#f)
table5
table5 %>% unite(new,century,year,sep="")


```

```{r}
#Que2
rm=(list=ls())
#install.packages("data.table")
library(data.table)
#a)
#fread=fast to read  && setDT
my_data <- fread("https://github.com/arunsrinivasan/satrdays-workshop/raw/master/flights_2014.csv")
  my_data

#b)
View(my_data)
head(my_data)
nrow(my_data)
ncol(my_data)
dim(my_data)
names(my_data)
#c)
as.data.table(my_data)

#d)
d_2 <- my_data[,c("origin","year","month","hour")]
print(d_2)
#e)
e_2 <- my_data[,!c("origin","year","month")]
e_2

#f)
f_2 <- setnames(my_data,c("dest","origin"),c("destination","origin.of.flight"))
f_2
f_2 <-  setnames(my_data,c("destination","origin.of.flight"),c("dest","origin"))
f_2

#g)
g_2 <- my_data[origin=="JFK"]
g_2

#h)
h_2 <- my_data[origin %in% c("JFK","LGA")]
h_2

#i)
i_2 <- my_data[origin=="JFK" & carrier=="AA"]
i_2

#j)
j_asc <- setorder(my_data,origin)
head(j_asc)
j_dec <- setorder(my_data,-origin)
head(j_dec)
#k)
k_2 <- setorder(my_data,origin,-carrier)
k_2

#l)
#to create one new variable named dep_sch
l_2 <- my_data[,dep_sch:=dep_time-dep_delay]
l_2
#to create 2 new variables named dep_sch annd arr_sch
l_2a <- my_data[,c("dep_sch","arr_sch"):=list(dep_time-dep_delay,arr_time-arr_delay)]
l_2a
#m)
m_2 <- my_data[,flag:=ifelse(min<50,"1","0")]
m_2

#n)
my_data[,.(mean_arr_delay=mean(arr_delay,na.rm=T),
           median_arr_delay=median(arr_delay,na.rm=T),
           min_arr_delay=min(arr_delay,na.rm=T),
           max_arr_delay=max(arr_delay,na.rm=T))]

#o)
my_data[,.(mean_arr_time=mean(arr_time,na.rm=T)),by=origin]

#p)
my_data[,.(mean_arr_time=mean(arr_time),mean_delay_time=mean(arr_delay)),by=origin]

#q)
setkey(my_data,"carrier")
unique(my_data)
dim(unique(my_data))
dim(my_data)
#r)
setkey(my_data,NULL)
unique(my_data)

#s)dataset[,.SD[1:2],by=colname]--to select particular row from the data if we add by at the last then it will give it by column
my_data[,.SD[.N],by=carrier]
#to no of rows wrt to categories of a column
my_data[,.N,by=carrier]
my_data[,.SD[1],by=origin] #first row

#t)
my_data[,.N,by=month][order(-N)]

#u)
my_data[,.(mean_arr_time=mean(arr_time,na.rm=T)),by=month][order(-mean_arr_time)][1:3]

#v)
my_data[,.(mean_arr_time=mean(arr_time),mean_delay_time=mean(arr_delay)),by=carrier][order(c('origin','dest'))]

```
